# Generated by Django 6.0.6 on 2026-07-15 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('note', 'Note'), ('video', 'Video'), ('quiz', 'Quiz')], max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('quiz_question', models.CharField(blank=True, max_length=500, null=True)),
                ('quiz_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapp.courses')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
